[FIX] account: allow preview for invoice with early discount and no date
## Issue
When clicking the *Preview* button on a draft invoice with an early discount
payment term and no invoice date, the following traceback would appear:

```
File ".../addons/account/models/account_payment_term.py", line 274, in _get_last_discount_date
    return date_ref + relativedelta(days=self.discount_days or 0) if self.early_discount else False
           ~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
TypeError: unsupported operand type(s) for +: 'bool' and 'relativedelta'
```

## Steps to reproduce
1. Install *Accounting* (`account_accountant`)
2. In Accounting > Configuration > Payment Terms, chose a Payment Term PT
and toggle its *Early Discount* field
3. In Accounting > Customers > Invoices, create **but do not confirm** a new Invoice
    - Any Customer
    - Payment Term PT
    - Any Product
    - **No Invoice Date**
4. Click the *Preview* button
5. **A _500: Internal Server Error_ traceback appears**

## Cause
The traceback occurs in `AccountPaymentTerm._get_last_discount_date`:

https://github.com/odoo/odoo/blob/6cc36886c612c7ed8878117637ee11bc6234d0e4/addons/account/models/account_payment_term.py#L272-L274

where `date_ref` is False. This method is called by `AccountMove._is_eligible_for_early_payment_discount`:

https://github.com/odoo/odoo/blob/6cc36886c612c7ed8878117637ee11bc6234d0e4/addons/account/models/account_move.py#L2026-L2032

where `self.invoice_date` is False, because that field is not required,
and the user can click the *Preview* button before a date is set. If the
invoice is confirmed before being previewed, the issue does not occur,
as confirming an invoice with no date will use today's date by default.
This is done in `AccountMove._post`:

https://github.com/odoo/odoo/blob/6cc36886c612c7ed8878117637ee11bc6234d0e4/addons/account/models/account_move.py#L3967-L3971

## Fix
We can apply the same behavior as if the invoice was confirmed, and use
today's date by default if no invoice date is given when trying to preview
a draft invoice. The same logic should be applied to
`_get_last_discount_date_formatted` for the date to be correctly evaluated
in `account/views/report_invoice.xml`:

https://github.com/odoo/odoo/blob/6cc36886c612c7ed8878117637ee11bc6234d0e4/addons/account/views/report_invoice.xml#L252-L254

where `o.invoice_date` is also `False`, leading to
`AccountPaymentTerm._get_last_discount_date_formatted` to return None:

https://github.com/odoo/odoo/blob/6cc36886c612c7ed8878117637ee11bc6234d0e4/addons/account/models/account_payment_term.py#L276-L280

which then displays the default date (`2024-01-01`) instead of
*today + the early discount time limit*.

opw-6008959

closes odoo/odoo#254338

Signed-off-by: Maximilien La Barre (malb) <malb@odoo.com>